# Generated by Django 5.2 on 2025-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
