# Generated by Django 5.2 on 2025-05-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0003_alter_match_away_team_alter_match_home_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_away', to='bowls_club.oppositionteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_home', to='bowls_club.oppositionteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_location', to='bowls_club.oppositionteam'),
        ),
    ]
