# Generated by Django 5.2 on 2025-05-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0004_alter_match_away_team_alter_match_home_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='location',
        ),
        migrations.AddField(
            model_name='match',
            name='home_or_away',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], default='Home', max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='opposition_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_opposition', to='bowls_club.oppositionteam'),
            preserve_default=False,
        ),
    ]
