# Generated by Django 5.2 on 2025-05-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0005_remove_match_away_team_remove_match_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
