# Generated by Django 5.2 on 2025-05-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0006_match_home_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score_away',
            new_name='crosshands_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score_home',
            new_name='opposition_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.AddField(
            model_name='oppositionteam',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='opposition_teams', to='bowls_club.competition'),
        ),
    ]
