# Generated by Django 5.2 on 2025-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0008_ownclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Captain', 'Captain'), ('Vice-Captain', 'Vice-Captain'), ('Player', 'Player'), ('Social', 'Social')], default='Player', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('Men', 'Men'), ('Ladies', 'Ladies'), ('Social', 'Social')], max_length=20),
        ),
    ]
