# Generated by Django 5.2 on 2025-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0009_member_profile_image_member_profile_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
