# Generated by Django 5.2 on 2025-05-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0010_sponsor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownclub',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bowls_club.competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='opposition_team',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rink',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rinks', to='bowls_club.match'),
        ),
        migrations.AlterField(
            model_name='rink',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rink',
            name='players',
            field=models.ManyToManyField(related_name='rinks', to='bowls_club.member'),
        ),
    ]
