# Generated by Django 5.2 on 2025-05-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0011_remove_ownclub_short_name_alter_match_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opposition_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bowls_club.oppositionteam'),
        ),
    ]
