# Generated by Django 5.2 on 2025-05-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0012_alter_match_opposition_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='rink',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinks_as_lead', to='bowls_club.member'),
        ),
        migrations.AddField(
            model_name='rink',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinks_as_second', to='bowls_club.member'),
        ),
        migrations.AddField(
            model_name='rink',
            name='skip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinks_as_skip', to='bowls_club.member'),
        ),
        migrations.AddField(
            model_name='rink',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinks_as_third', to='bowls_club.member'),
        ),
        migrations.AlterField(
            model_name='rink',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='rinks', to='bowls_club.member'),
        ),
    ]
