# Generated by Django 5.2 on 2025-05-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0013_rink_lead_rink_second_rink_skip_rink_third_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='crosshands_score',
            new_name='our_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='opposition_score',
            new_name='their_score',
        ),
    ]
