# Generated by Django 5.2 on 2025-05-26 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowls_club', '0015_matchavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchavailability',
            unique_together={('match', 'user')},
        ),
    ]
